print("Hello World")
print("Welcome to Git!")
print("Git is a popular version control system")
print("Successfully set up a local Git repository onto GitHub")
print("A change has been made from a pull request for Tanmay")